version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@yummacss/core"
      - dependency-name: "yummacss"
    groups:
      yummacss-updates:
        patterns:
          - "@yummacss/core"
          - "yummacss"
